### ISSUE TITLE
Folder child-parent funktioniert nicht

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#32]
# Status quo
Beispielconfig `folders`:

```json
...
	"folders":
	[
               ...
		{ "id": "fachdaten", "title": "Geofachdaten", "parent": null },
		{ "id": "ksp", "title": "Kompensationsverzeichnis", "parent": "fachdaten" },
		{ "id": "kom", "title": "Kompensationen", "parent": "ksp" },
                ...
	],

```

Man würde erwarten, dass die Ordnerstruktur wie folgt aussieht:

* "Geofachdaten"
    * "Kompensationsverzeichnis"
        * "KSP"

Aber aktuell scheinen Ordner nicht in eine reine folder Hierarchie gebracht werden zu können. Das Ergebnis im Client sieht so aus:

![grafik](https://github.com/user-attachments/assets/90356fa4-8d12-4bf8-b306-fa37a6c4647c)

Testweise habe ich auch geprüft, ob das `parent` Attribut noch über die Indexstelle im Array aufgelöst wird (z.B. `"parent": 4`) aber auch das bringt die Ordner nicht untereinander.

**Comment by sebastianpauli** [comment]
Should be fixed in latest [commit](https://github.com/sebastianpauli/netgis-client/commit/bb4bc31d8a915176848856014e29297fd585f2cb).

The folder hierarchy should now properly respect the config folders parent ids.

Example:

```
"folders":
[
	{ "id": "test", "title": "Test", "parent": null, "radio": false },
	{ "id": "test2", "title": "Test 2", "parent": "test", "radio": false },
	{ "id": "test3", "title": "Test 3", "parent": "test2", "radio": false },
	{ "id": "bg", "title": "Hintergrund", "parent": null, "radio": true }
]
```
Should result in a tree structure like this:

![grafik](https://github.com/user-attachments/assets/45e9fbe5-c8c7-415c-95e7-99462f117e1d)

**Comment by Rastopapola** [comment]
Works as expected. Thanks!
